Better handling for configuration related errors
Fix for 
```
(node:14343) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at printMigrated (~/node_modules/migrate-mongo/bin/migrate-mongo.js:10:12)
    at migrateMongo.database.connect.then.then.catch.err (~/node_modules/migrate-mongo/bin/migrate-mongo.js:74:9)
```

That was caused by errors like
> Error: config file does not exist
> MongoError: collection name must be a String
etc.